services:
  - type: web
    name: panol-monolith-service
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SPREADSHEET_ID
        value: 1aKptNgy8a9Ca3rDW-HSlWEiriMRJMOIJuFsdViwEGFc
      - key: NODE_ENV
        value: production
